// Centralized icon registry — import icons from here, never from lucide-react directly in pages
// Organized by business domain for discoverability

export {
  // ── Navigation & Layout ─────────────────────────────────────────
  LayoutDashboard,
  LayoutGrid,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  SidebarClose,
  SidebarOpen,
  PanelLeft,

  // ── Actions ─────────────────────────────────────────────────────
  Plus,
  Minus,
  Edit,
  Trash2,
  Copy,
  Save,
  Upload,
  Download,
  RefreshCw,
  RotateCcw,
  Check,
  CheckCircle2,
  XCircle,
  ExternalLink,
  Link,
  Share2,
  ArrowUpRight,
  ArrowLeft,
  ArrowRight,
  Move,
  GripVertical,
  MoreHorizontal,
  MoreVertical,
  Expand,
  Shrink,
  Maximize2,
  Minimize2,

  // ── Data & Files ────────────────────────────────────────────────
  FileText,
  File,
  Folder,
  FolderOpen,
  FolderPlus,
  Archive,
  Paperclip,
  Package,
  Database,
  Table2,
  List,
  BarChart3,
  BarChart2,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,

  // ── User & Organization ─────────────────────────────────────────
  User,
  Users,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Building2,
  Crown,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Lock,
  Unlock,
  Key,
  LogIn,
  LogOut,

  // ── Assets & Inventory ──────────────────────────────────────────
  Boxes,
  PackagePlus,
  PackageCheck,
  PackageX,
  PackageSearch,
  QrCode,
  Tag,
  Tags,
  Barcode,
  ScanLine,

  // ── Maintenance & Operations ────────────────────────────────────
  Wrench,
  WrenchIcon,
  Hammer,
  // Tool removed — use Wrench instead
  Settings,
  Settings2,
  Cog,
  Gauge,
  ClipboardList,
  ClipboardCheck,
  ClipboardX,
  Clipboard,

  // ── Procurement & Finance ───────────────────────────────────────
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  DollarSign,
  Receipt,
  Calculator,
  Wallet,
  Coins,
  BadgeDollarSign,
  CircleDollarSign,

  // ── Location & Maps ─────────────────────────────────────────────
  MapPin,
  Map,
  Navigation,
  Building,
  Warehouse,
  Home,
  Factory,
  Hotel,

  // ── Time & Calendar ─────────────────────────────────────────────
  Calendar,
  CalendarDays,
  CalendarClock,
  Clock,
  Clock3,
  Timer,
  AlarmClock,

  // ── Communication & Feedback ────────────────────────────────────
  Bell,
  BellOff,
  BellRing,
  Mail,
  MessageSquare,
  MessageCircle,
  Send,
  Megaphone,
  Flag,
  Bookmark,
  Star,
  ThumbsUp,
  ThumbsDown,

  // ── Status & Alerts ─────────────────────────────────────────────
  AlertTriangle,
  AlertCircle,
  AlertOctagon,
  Info,
  HelpCircle,
  CheckCircle,
  XOctagon,
  Loader2,
  Loader,
  // Spinner removed — use Loader2 instead

  // ── Search & Filter ─────────────────────────────────────────────
  Search,
  Filter,
  SlidersHorizontal,
  SortAsc,
  SortDesc,
  ArrowUpDown,

  // ── Appearance & Theme ──────────────────────────────────────────
  Sun,
  Moon,
  Monitor,
  Palette,
  Paintbrush,
  Eye,
  EyeOff,
  ZoomIn,
  ZoomOut,

  // ── Misc ────────────────────────────────────────────────────────
  Inbox,
  InboxIcon,
  Layers,
  Network,
  Plug,
  Cpu,
  Globe,
  Wifi,
  WifiOff,
  Power,
  Zap,
  Code2,
  Code,
  Terminal,
  Hash,
  AtSign,
  Percent,
  Slash,
  Dot,
  Circle,
  Square,
  Triangle,
  Minus as HorizontalRule,
  Grip,
  Image,
  ImagePlus,
  Video,
  Mic,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  Grid3X3,
  LayoutList,
} from 'lucide-react';

export type { LucideIcon, LucideProps } from 'lucide-react';
