import { UserRole } from '@/types/auth';
import { Permission } from '@/constants/permissions';

export type PermissionMatrix = Record<UserRole, Permission[]>;

// ─── Role → Permissions Matrix ─────────────────────────────────────────────────

export const permissionsConfig: PermissionMatrix = {

  [UserRole.ADMIN]: [
    Permission.ASSETS_CREATE,
    Permission.ASSETS_READ,
    Permission.ASSETS_UPDATE,
    Permission.ASSETS_DELETE,
    Permission.ASSETS_EXPORT,
    Permission.ASSETS_IMPORT,
    Permission.ASSETS_RETIRE,
    Permission.ASSETS_TRANSFER,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_READ,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_DELETE,
    Permission.MAINTENANCE_ASSIGN,
    Permission.MAINTENANCE_APPROVE,
    Permission.PROCUREMENT_CREATE,
    Permission.PROCUREMENT_READ,
    Permission.PROCUREMENT_UPDATE,
    Permission.PROCUREMENT_DELETE,
    Permission.PROCUREMENT_APPROVE,
    Permission.PROCUREMENT_REJECT,
    Permission.DEPRECIATION_READ,
    Permission.DEPRECIATION_MANAGE,
    Permission.DEPRECIATION_POST,
    Permission.LOCATIONS_CREATE,
    Permission.LOCATIONS_READ,
    Permission.LOCATIONS_UPDATE,
    Permission.LOCATIONS_DELETE,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.REPORTS_SCHEDULE,
    Permission.AUDIT_READ,
    Permission.AUDIT_EXPORT,
    Permission.USERS_CREATE,
    Permission.USERS_READ,
    Permission.USERS_UPDATE,
    Permission.USERS_DELETE,
    Permission.USERS_MANAGE_ROLES,
    Permission.ORG_READ,
    Permission.ORG_UPDATE,
    Permission.ORG_MANAGE_SETTINGS,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_UPDATE,
  ],

  [UserRole.ASSET_MANAGER]: [
    Permission.ASSETS_CREATE,
    Permission.ASSETS_READ,
    Permission.ASSETS_UPDATE,
    Permission.ASSETS_DELETE,
    Permission.ASSETS_EXPORT,
    Permission.ASSETS_IMPORT,
    Permission.ASSETS_RETIRE,
    Permission.ASSETS_TRANSFER,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_READ,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_ASSIGN,
    Permission.MAINTENANCE_APPROVE,
    Permission.PROCUREMENT_CREATE,
    Permission.PROCUREMENT_READ,
    Permission.PROCUREMENT_UPDATE,
    Permission.DEPRECIATION_READ,
    Permission.DEPRECIATION_MANAGE,
    Permission.LOCATIONS_CREATE,
    Permission.LOCATIONS_READ,
    Permission.LOCATIONS_UPDATE,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.AUDIT_READ,
    Permission.USERS_READ,
    Permission.ORG_READ,
    Permission.SETTINGS_READ,
  ],

  [UserRole.DEPARTMENT_HEAD]: [
    Permission.ASSETS_READ,
    Permission.ASSETS_UPDATE,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_READ,
    Permission.MAINTENANCE_UPDATE,
    Permission.PROCUREMENT_READ,
    Permission.DEPRECIATION_READ,
    Permission.LOCATIONS_READ,
    Permission.REPORTS_VIEW,
    Permission.USERS_READ,
    Permission.ORG_READ,
    Permission.SETTINGS_READ,
  ],

  [UserRole.EMPLOYEE]: [
    Permission.ASSETS_READ,
    Permission.MAINTENANCE_READ,
    Permission.PROCUREMENT_READ,
    Permission.DEPRECIATION_READ,
    Permission.LOCATIONS_READ,
    Permission.REPORTS_VIEW,
    Permission.ORG_READ,
    Permission.SETTINGS_READ,
  ],
};

// ─── Permission Labels for UI ──────────────────────────────────────────────────

export const permissionsMetadata: Partial<Record<Permission, { label: string; module: string; description: string }>> = {
  [Permission.ASSETS_CREATE]:       { label: 'Create Assets',       module: 'Assets',       description: 'Register new asset records' },
  [Permission.ASSETS_READ]:         { label: 'View Assets',         module: 'Assets',       description: 'View asset list and details' },
  [Permission.ASSETS_UPDATE]:       { label: 'Update Assets',       module: 'Assets',       description: 'Edit existing asset records' },
  [Permission.ASSETS_DELETE]:       { label: 'Delete Assets',       module: 'Assets',       description: 'Soft-delete asset records' },
  [Permission.ASSETS_EXPORT]:       { label: 'Export Assets',       module: 'Assets',       description: 'Export asset data to CSV' },
  [Permission.ASSETS_IMPORT]:       { label: 'Import Assets',       module: 'Assets',       description: 'Bulk import asset records' },
  [Permission.ASSETS_RETIRE]:       { label: 'Retire Assets',       module: 'Assets',       description: 'Mark assets as retired' },
  [Permission.ASSETS_TRANSFER]:     { label: 'Transfer Assets',     module: 'Assets',       description: 'Transfer assets between locations' },
  [Permission.MAINTENANCE_CREATE]:  { label: 'Create Maintenance',  module: 'Maintenance',  description: 'Create maintenance work orders' },
  [Permission.MAINTENANCE_READ]:    { label: 'View Maintenance',    module: 'Maintenance',  description: 'View maintenance orders' },
  [Permission.MAINTENANCE_UPDATE]:  { label: 'Update Maintenance',  module: 'Maintenance',  description: 'Edit maintenance orders' },
  [Permission.MAINTENANCE_DELETE]:  { label: 'Delete Maintenance',  module: 'Maintenance',  description: 'Delete maintenance records' },
  [Permission.MAINTENANCE_ASSIGN]:  { label: 'Assign Maintenance',  module: 'Maintenance',  description: 'Assign work to technicians' },
  [Permission.MAINTENANCE_APPROVE]: { label: 'Approve Maintenance', module: 'Maintenance',  description: 'Approve maintenance requests' },
  [Permission.PROCUREMENT_CREATE]:  { label: 'Create Procurement',  module: 'Procurement',  description: 'Create procurement requests' },
  [Permission.PROCUREMENT_READ]:    { label: 'View Procurement',    module: 'Procurement',  description: 'View procurement requests' },
  [Permission.PROCUREMENT_UPDATE]:  { label: 'Update Procurement',  module: 'Procurement',  description: 'Edit procurement requests' },
  [Permission.PROCUREMENT_DELETE]:  { label: 'Delete Procurement',  module: 'Procurement',  description: 'Delete procurement records' },
  [Permission.PROCUREMENT_APPROVE]: { label: 'Approve Procurement', module: 'Procurement',  description: 'Approve procurement requests' },
  [Permission.PROCUREMENT_REJECT]:  { label: 'Reject Procurement',  module: 'Procurement',  description: 'Reject procurement requests' },
  [Permission.DEPRECIATION_READ]:   { label: 'View Depreciation',   module: 'Depreciation', description: 'View depreciation schedules' },
  [Permission.DEPRECIATION_MANAGE]: { label: 'Manage Depreciation', module: 'Depreciation', description: 'Create/edit depreciation schedules' },
  [Permission.DEPRECIATION_POST]:   { label: 'Post Depreciation',   module: 'Depreciation', description: 'Execute depreciation runs' },
  [Permission.LOCATIONS_CREATE]:    { label: 'Create Locations',    module: 'Locations',    description: 'Create new locations' },
  [Permission.LOCATIONS_READ]:      { label: 'View Locations',      module: 'Locations',    description: 'View location hierarchy' },
  [Permission.LOCATIONS_UPDATE]:    { label: 'Update Locations',    module: 'Locations',    description: 'Edit location details' },
  [Permission.LOCATIONS_DELETE]:    { label: 'Delete Locations',    module: 'Locations',    description: 'Remove locations' },
  [Permission.REPORTS_VIEW]:        { label: 'View Reports',        module: 'Reports',      description: 'View reports and analytics' },
  [Permission.REPORTS_EXPORT]:      { label: 'Export Reports',      module: 'Reports',      description: 'Export report data' },
  [Permission.REPORTS_SCHEDULE]:    { label: 'Schedule Reports',    module: 'Reports',      description: 'Schedule recurring reports' },
  [Permission.AUDIT_READ]:          { label: 'View Audit Log',      module: 'Audit',        description: 'View audit trail' },
  [Permission.AUDIT_EXPORT]:        { label: 'Export Audit Log',    module: 'Audit',        description: 'Export audit log data' },
  [Permission.USERS_CREATE]:        { label: 'Invite Users',        module: 'Users',        description: 'Invite new team members' },
  [Permission.USERS_READ]:          { label: 'View Users',          module: 'Users',        description: 'View team members' },
  [Permission.USERS_UPDATE]:        { label: 'Update Users',        module: 'Users',        description: 'Edit user profiles' },
  [Permission.USERS_DELETE]:        { label: 'Remove Users',        module: 'Users',        description: 'Deactivate member accounts' },
  [Permission.USERS_MANAGE_ROLES]:  { label: 'Manage Roles',        module: 'Users',        description: 'Change member roles' },
  [Permission.ORG_READ]:            { label: 'View Organization',   module: 'Organization', description: 'View org settings' },
  [Permission.ORG_UPDATE]:          { label: 'Update Organization', module: 'Organization', description: 'Edit org settings' },
  [Permission.ORG_MANAGE_SETTINGS]: { label: 'Manage Org Settings', module: 'Organization', description: 'Full org configuration access' },
  [Permission.SETTINGS_READ]:       { label: 'View Settings',       module: 'Settings',     description: 'View system settings' },
  [Permission.SETTINGS_UPDATE]:     { label: 'Update Settings',     module: 'Settings',     description: 'Modify system settings' },
};
