import { UserRole } from '@/types/auth';
import { Permission } from '@/constants/permissions';

export type PermissionMatrix = Record<UserRole, Permission[]>;

export const permissionsConfig: PermissionMatrix = {
  [UserRole.SUPER_ADMIN]: Object.values(Permission),

  [UserRole.ORG_ADMIN]: [
    // Assets
    Permission.ASSET_VIEW,
    Permission.ASSET_CREATE,
    Permission.ASSET_UPDATE,
    Permission.ASSET_DELETE,
    Permission.ASSET_EXPORT,
    Permission.ASSET_IMPORT,
    Permission.ASSET_ASSIGN,
    Permission.ASSET_TRANSFER,
    Permission.ASSET_RETIRE,
    // Maintenance
    Permission.MAINTENANCE_VIEW,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_DELETE,
    Permission.MAINTENANCE_ASSIGN,
    Permission.MAINTENANCE_APPROVE,
    Permission.MAINTENANCE_COMPLETE,
    // Procurement
    Permission.PROCUREMENT_VIEW,
    Permission.PROCUREMENT_CREATE,
    Permission.PROCUREMENT_UPDATE,
    Permission.PROCUREMENT_DELETE,
    Permission.PROCUREMENT_APPROVE,
    Permission.PROCUREMENT_EXPORT,
    // Depreciation
    Permission.DEPRECIATION_VIEW,
    Permission.DEPRECIATION_CREATE,
    Permission.DEPRECIATION_UPDATE,
    Permission.DEPRECIATION_DELETE,
    Permission.DEPRECIATION_RUN,
    Permission.DEPRECIATION_EXPORT,
    // Locations
    Permission.LOCATION_VIEW,
    Permission.LOCATION_CREATE,
    Permission.LOCATION_UPDATE,
    Permission.LOCATION_DELETE,
    // Reports
    Permission.REPORT_VIEW,
    Permission.REPORT_CREATE,
    Permission.REPORT_EXPORT,
    Permission.REPORT_SCHEDULE,
    // Audit
    Permission.AUDIT_VIEW,
    Permission.AUDIT_EXPORT,
    // Users
    Permission.USER_VIEW,
    Permission.USER_INVITE,
    Permission.USER_UPDATE,
    Permission.USER_DEACTIVATE,
    Permission.USER_ROLE_CHANGE,
    // Org & Settings
    Permission.ORG_VIEW,
    Permission.ORG_UPDATE,
    Permission.SETTINGS_VIEW,
    Permission.SETTINGS_UPDATE,
  ],

  [UserRole.ASSET_MANAGER]: [
    Permission.ASSET_VIEW,
    Permission.ASSET_CREATE,
    Permission.ASSET_UPDATE,
    Permission.ASSET_EXPORT,
    Permission.ASSET_IMPORT,
    Permission.ASSET_ASSIGN,
    Permission.ASSET_TRANSFER,
    Permission.MAINTENANCE_VIEW,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_ASSIGN,
    Permission.MAINTENANCE_COMPLETE,
    Permission.PROCUREMENT_VIEW,
    Permission.PROCUREMENT_CREATE,
    Permission.PROCUREMENT_UPDATE,
    Permission.PROCUREMENT_EXPORT,
    Permission.DEPRECIATION_VIEW,
    Permission.DEPRECIATION_CREATE,
    Permission.DEPRECIATION_RUN,
    Permission.DEPRECIATION_EXPORT,
    Permission.LOCATION_VIEW,
    Permission.LOCATION_CREATE,
    Permission.LOCATION_UPDATE,
    Permission.REPORT_VIEW,
    Permission.REPORT_CREATE,
    Permission.REPORT_EXPORT,
    Permission.USER_VIEW,
    Permission.ORG_VIEW,
    Permission.SETTINGS_VIEW,
  ],

  [UserRole.TECHNICIAN]: [
    Permission.ASSET_VIEW,
    Permission.ASSET_UPDATE,
    Permission.MAINTENANCE_VIEW,
    Permission.MAINTENANCE_CREATE,
    Permission.MAINTENANCE_UPDATE,
    Permission.MAINTENANCE_COMPLETE,
    Permission.LOCATION_VIEW,
    Permission.REPORT_VIEW,
    Permission.ORG_VIEW,
  ],

  [UserRole.VIEWER]: [
    Permission.ASSET_VIEW,
    Permission.MAINTENANCE_VIEW,
    Permission.PROCUREMENT_VIEW,
    Permission.DEPRECIATION_VIEW,
    Permission.LOCATION_VIEW,
    Permission.REPORT_VIEW,
    Permission.ORG_VIEW,
  ],
};

export const permissionsMetadata: Record<Permission, { label: string; module: string; description: string }> = {
  [Permission.ASSET_VIEW]:         { label: 'View Assets',         module: 'Assets',       description: 'View asset list and details' },
  [Permission.ASSET_CREATE]:       { label: 'Create Assets',       module: 'Assets',       description: 'Create new asset records' },
  [Permission.ASSET_UPDATE]:       { label: 'Update Assets',       module: 'Assets',       description: 'Edit existing asset records' },
  [Permission.ASSET_DELETE]:       { label: 'Delete Assets',       module: 'Assets',       description: 'Soft-delete asset records' },
  [Permission.ASSET_EXPORT]:       { label: 'Export Assets',       module: 'Assets',       description: 'Export asset data to CSV/Excel' },
  [Permission.ASSET_IMPORT]:       { label: 'Import Assets',       module: 'Assets',       description: 'Bulk import asset records' },
  [Permission.ASSET_ASSIGN]:       { label: 'Assign Assets',       module: 'Assets',       description: 'Assign assets to users/locations' },
  [Permission.ASSET_TRANSFER]:     { label: 'Transfer Assets',     module: 'Assets',       description: 'Transfer assets between locations' },
  [Permission.ASSET_RETIRE]:       { label: 'Retire Assets',       module: 'Assets',       description: 'Mark assets as retired' },
  [Permission.MAINTENANCE_VIEW]:   { label: 'View Maintenance',    module: 'Maintenance',  description: 'View maintenance orders' },
  [Permission.MAINTENANCE_CREATE]: { label: 'Create Maintenance',  module: 'Maintenance',  description: 'Create maintenance orders' },
  [Permission.MAINTENANCE_UPDATE]: { label: 'Update Maintenance',  module: 'Maintenance',  description: 'Edit maintenance orders' },
  [Permission.MAINTENANCE_DELETE]: { label: 'Delete Maintenance',  module: 'Maintenance',  description: 'Delete maintenance orders' },
  [Permission.MAINTENANCE_ASSIGN]: { label: 'Assign Maintenance',  module: 'Maintenance',  description: 'Assign work orders to technicians' },
  [Permission.MAINTENANCE_APPROVE]:{ label: 'Approve Maintenance', module: 'Maintenance',  description: 'Approve maintenance requests' },
  [Permission.MAINTENANCE_COMPLETE]:{ label: 'Complete Maintenance',module: 'Maintenance', description: 'Mark maintenance orders complete' },
  [Permission.PROCUREMENT_VIEW]:   { label: 'View Procurement',    module: 'Procurement',  description: 'View procurement requests' },
  [Permission.PROCUREMENT_CREATE]: { label: 'Create Procurement',  module: 'Procurement',  description: 'Create procurement requests' },
  [Permission.PROCUREMENT_UPDATE]: { label: 'Update Procurement',  module: 'Procurement',  description: 'Edit procurement requests' },
  [Permission.PROCUREMENT_DELETE]: { label: 'Delete Procurement',  module: 'Procurement',  description: 'Delete procurement requests' },
  [Permission.PROCUREMENT_APPROVE]:{ label: 'Approve Procurement', module: 'Procurement',  description: 'Approve/reject procurement requests' },
  [Permission.PROCUREMENT_EXPORT]: { label: 'Export Procurement',  module: 'Procurement',  description: 'Export procurement data' },
  [Permission.DEPRECIATION_VIEW]:  { label: 'View Depreciation',   module: 'Depreciation', description: 'View depreciation schedules' },
  [Permission.DEPRECIATION_CREATE]:{ label: 'Create Depreciation', module: 'Depreciation', description: 'Create depreciation schedules' },
  [Permission.DEPRECIATION_UPDATE]:{ label: 'Update Depreciation', module: 'Depreciation', description: 'Edit depreciation schedules' },
  [Permission.DEPRECIATION_DELETE]:{ label: 'Delete Depreciation', module: 'Depreciation', description: 'Delete depreciation entries' },
  [Permission.DEPRECIATION_RUN]:   { label: 'Run Depreciation',    module: 'Depreciation', description: 'Execute depreciation calculations' },
  [Permission.DEPRECIATION_EXPORT]:{ label: 'Export Depreciation', module: 'Depreciation', description: 'Export depreciation reports' },
  [Permission.LOCATION_VIEW]:      { label: 'View Locations',      module: 'Locations',    description: 'View location hierarchy' },
  [Permission.LOCATION_CREATE]:    { label: 'Create Locations',    module: 'Locations',    description: 'Create new locations' },
  [Permission.LOCATION_UPDATE]:    { label: 'Update Locations',    module: 'Locations',    description: 'Edit location details' },
  [Permission.LOCATION_DELETE]:    { label: 'Delete Locations',    module: 'Locations',    description: 'Delete locations' },
  [Permission.REPORT_VIEW]:        { label: 'View Reports',        module: 'Reports',      description: 'View reports and analytics' },
  [Permission.REPORT_CREATE]:      { label: 'Create Reports',      module: 'Reports',      description: 'Create custom reports' },
  [Permission.REPORT_EXPORT]:      { label: 'Export Reports',      module: 'Reports',      description: 'Export report data' },
  [Permission.REPORT_SCHEDULE]:    { label: 'Schedule Reports',    module: 'Reports',      description: 'Schedule recurring reports' },
  [Permission.AUDIT_VIEW]:         { label: 'View Audit Log',      module: 'Audit',        description: 'View audit trail' },
  [Permission.AUDIT_EXPORT]:       { label: 'Export Audit Log',    module: 'Audit',        description: 'Export audit log data' },
  [Permission.USER_VIEW]:          { label: 'View Users',          module: 'Users',        description: 'View team members' },
  [Permission.USER_INVITE]:        { label: 'Invite Users',        module: 'Users',        description: 'Invite new members' },
  [Permission.USER_UPDATE]:        { label: 'Update Users',        module: 'Users',        description: 'Edit user profiles' },
  [Permission.USER_DEACTIVATE]:    { label: 'Deactivate Users',    module: 'Users',        description: 'Deactivate member accounts' },
  [Permission.USER_ROLE_CHANGE]:   { label: 'Change User Roles',   module: 'Users',        description: 'Change member roles' },
  [Permission.ORG_VIEW]:           { label: 'View Organization',   module: 'Organization', description: 'View org settings' },
  [Permission.ORG_UPDATE]:         { label: 'Update Organization', module: 'Organization', description: 'Edit org settings' },
  [Permission.ORG_DELETE]:         { label: 'Delete Organization', module: 'Organization', description: 'Delete the organization' },
  [Permission.SETTINGS_VIEW]:      { label: 'View Settings',       module: 'Settings',     description: 'View system settings' },
  [Permission.SETTINGS_UPDATE]:    { label: 'Update Settings',     module: 'Settings',     description: 'Modify system settings' },
  [Permission.SUPER_ADMIN_ACCESS]: { label: 'Super Admin',         module: 'Admin',        description: 'Full platform access' },
};
